### ISSUE TITLE
custom cache invalidation via hook_cron

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/recserv.uiowa.edu#22]
First, consider if using the APE module makes sense and keep the api endpoint and the facility/area nodes at a lower default cache lifetime of 1 hour makes sense to start. If that's good enough, great! If not, you could keep the cache lifetime set to 6 hours, and use cron to check the several external endpoints to see if they've changed, and then if so, invalidate the endpoints, locations view, and individual nodes as explained below. I'm guessing just using APE may not be enough, considering there may be instances where they want to show the Rainoutline info much quicker.

Utilize hook_cron() to implement custom cache invalidation for the api/v1.0/locations end point and individual resources underneath it.

Setup elysia cron at a fairly regular interval to check if we should invalidate the cache.

**Comment by adamdelaney** [comment]
I have enabled APE on the staging environment and setup an alternative caching scheme for 1 hour for the following paths:
- <front>
- facilities
- facilities/*
- intramural-sports
