### ISSUE TITLE
delete uiowa_hours module

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/recserv.uiowa.edu#24]
no longer being used. update hook disables and uninstalls it. not exactly sure how you're handling deleting modules.

**Comment by adamdelaney** [comment]
I don't believe we needed to disable and uninstall because I don't think we were using this in production, but it doesn't hurt anything so I'm leaving the update hook. I've moved the module from modules/custom to modules/modules_to_delete.
