### ISSUE TITLE
List of questions for RecServ

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/recserv.uiowa.edu#9]
- What are we doing for homepage hours?

**Comment by brandonneil** [comment]
> Can we remove permissions to create content?
> Article
> Notification
> Testimonial

Yes

> Do we need the program type taxonomy?
> There is only 1 term in there: Community Programs
We can remove it

> Do we need the tags taxonomy?
> This field is only used on articles which we are deprecating.
> We may want to use on blog?
Let's reuse it on the blog, but delete all terms out of it first.

**Comment by adamdelaney** [comment]
>Does policy content need to be re-usable?
No it does not.

**Comment by adamdelaney** [comment]
>Do we still need Google Analytics Event Tracking?

No

**Comment by adamdelaney** [comment]
>Do we still want the social media embedded widgets?

No

**Comment by adamdelaney** [comment]
>Should people be implemented as basic pages?

Yes using directory listing paragraph widgets

**Comment by adamdelaney** [comment]
Date order for facility
Add hover label for location and rainout.

**Comment by adamdelaney** [comment]
>Are the rainout determination times static

Yes

**Comment by adamdelaney** [comment]
> What are our options for mapping if the facility does not show up in sitenow_maps

RecServ is responsible for getting FM to add any additional facilities.
